version: '3.8'

services:
  scg-mandate:
    build: .
    container_name: scg-mandate
    restart: unless-stopped
    ports:
      - "3010:80"
    networks:
      - scg-net

networks:
  scg-net:
    name: scg-platform_scg-net
    external: true
